### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by rayteale** [benkeen/generatedata#222]
Installation.    install.php  Step 1.  

Enter Mysql details. Get unhelpful "Uh-Oh" error

host name "localhost"
database name "fakedata"
user name "ray"
password "xxxxx"
Rest is default

Command line:  $> mysql -u ray -h localhost -pxxxxx fakedata    --  works OK.

Mysqwl Version 5.5.37-0ubuntu0.12.04.1

**Comment by gkrinc** [comment]
Same here...

This is the error logged by PHP

```
#0 /var/www/generatedata/resources/classes/Database.class.php(59): PDO->prepare('\n\t\t\tSELECT sett...')
#1 /var/www/generatedata/resources/classes/Settings.class.php(41): Database->query('\n\t\t\tSELECT sett...')
#2 /var/www/generatedata/resources/classes/Core.class.php(310): Settings::getSetting('installationCom...')
#3 /var/www/generatedata/resources/classes/SessionManager.class.php(13): Core::checkIsInstalled()
#4 /var/www/generatedata/resources/classes/Core.class.php(509): SessionManager->__construct()
#5 /var/www/generatedata/resources/classes/Core.class.php(130): Core::initSessions()
#6 /var/www/generatedata/resources/classes/AjaxRequest.class.php(72): Core::init('installationDat...')
#7 /var/www/generatedata/ajax.php(14): AjaxRequest->__construct('installationCre...', Array)
#8 {main}
  thrown in /var/www/generatedata/resources/classes/Database.class.php on line 59
```

**Comment by glad2badad** [comment]
The function that is throwing an error at you is testDbSettings which takes the dbhostname, dbname, dbusername, and dbpassword as parameters.  Something if failing with your db connection it appears.  Check the various values in there the next time you pull it up and see what you get.
