### ISSUE TITLE
Error trying to run yarn startApp on Ubuntu 22.04

### ISSUE THREAD

**Issue by robotalec** [benkeen/generatedata#839]
when running the yarn startApp on ubuntu 22.04 I get this error

yarn run v1.22.19
warning ../package.json: No license field
$ yarn prod && COMPOSE_HTTP_TIMEOUT=150 docker-compose -f docker-compose-prod.yml up --build
warning ../package.json: No license field
$ cd client && yarn build && grunt && yarn webpackProd
warning ../package.json: No license field
$ node ./client/build/build.js && yarn buildPackage
(node:54606) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, open '/home/amtelco/generatedata/server/database/_dbStructure.sql'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at createDatabaseInitFile (/home/amtelco/generatedata/client/build/build.js:248:5)
(node:54606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:54606) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
warning ../package.json: No license field
$ yarn --cwd cli build
warning package.json: No license field
warning ../../package.json: No license field
$ npx grunt && tsc
Running "clean:dist" (clean) task
>> 1 path cleaned.

Running "createEmptyDist" task

Running "copy:i18n" (copy) task
Copied 12 files

Running "i18n" task

Done.
/bin/sh: 1: tsc: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by benkeen** [comment]
Thanks @robotalec, sorry for the wait. This looks like a bug with the newer code for the not-yet-released CLI code. I'll get back to you.
